### ISSUE TITLE
Oura mockups 

### ISSUE THREAD

**Issue by prifina-admin** [libertyequalitydata/dynamic-data#13]
Could add this value too... score_resting_hr

https://github.com/libertyequalitydata/dynamic-data/blob/240409424aee2b0c704e18f7c0a3a554b5568c26/packages/oura-mockups/src/ouraMockups.js#L36

**Comment by Dylan-Finney** [comment]
Oura mockup additions for the ReadinessSummaryModel and SleepSummaryModel have been added in #14

**Comment by Dylan-Finney** [comment]
Oura mockup additions for the ReadinessSummaryModel and SleepSummaryModel have been added in #14
